Integration tests
SNL-WaterPower/WecOptTool pull request #164
Opened 2022-11-23 20:06 UTC by ryancoe

Closes #158 

## Checklist for PR
- [x] Authors read the [contribution guidelines](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [x] The pull request is from an issue branch (not main) on *your* fork, to the [main branch in WecOptTool](https://github.com/SNL-WaterPower/WecOptTool).
- [x] The authors have given the admins edit access
- [x] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [ ] Modified the documentation if applicable
- [ ] Modified or added a new test
- [ ] All tests pass
- [x] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

2022-12-01 23:01 UTC, ryancoe commented on tests/test_integration.py
> +                                       optim_options={'maxiter': 3})
@cmichelenstrofer - this is a bit odd here... without the iteration limit, these solves each run for different numbers of iterations, and then produce different results. Not surprisingly, `from_bem` and `from_floatingbody` appear identical to the solver, but `from_impedance` is slightly different... 

```
Optimization terminated successfully    (Exit mode 0)
            Current function value: -134.12455351141367
            Iterations: 23
            Function evaluations: 23
            Gradient evaluations: 23
Optimization terminated successfully    (Exit mode 0)
            Current function value: -134.12455351141367
            Iterations: 23
            Function evaluations: 23
            Gradient evaluations: 23
Optimization terminated successfully    (Exit mode 0)
            Current function value: -140.0013844455055
            Iterations: 24
            Function evaluations: 24
            Gradient evaluations: 24
```

My solution of limiting the iterations seems like a bit of a hack, but I think it is somewhat defensible. Perhaps a more elegant way to check the equivalence of these objects would be to break out the following lines for evaluating the residual into a hidden function and then call that for each of the object with the same random `x_wec` and `x_opt` arrays (i.e., basically check that for the same input, you get the same output).

https://github.com/SNL-WaterPower/WecOptTool/blob/fac42f78ddf485cac23f55986d5d6ae2923954d3/wecopttool/core.py#L726-L737

2022-12-01 23:38 UTC, ryancoe commented on tests/test_integration.py
> +                                       optim_options={'maxiter': 3})
Did this with 2af7098, appears to work. I suppose there's a lower level of integration in test now, but I think that's OK.

2022-12-02 17:26 UTC, cmichelenstrofer commented on tests/test_integration.py
> +                                       optim_options={'maxiter': 3})
I would expect the number of iterations to be different for `from_impedance`. The problem is setup quite differently. The other two should be identical. The difference in the solution between `from_impedance` and the others is too large, I don't think it is just an optimizer thing... My first suspicion would be that for the first two methods we are adding additional friction (to ensure it is always positive) but we don't do the same for `from_impedance`.

2022-12-02 21:18 UTC, ryancoe commented on tests/test_integration.py
> +                                       optim_options={'maxiter': 3})
You were right @cmichelenstrofer, `from_impedance` never calls `check_linear_damping` like the other two init methods do. With 85c55bc, I've added a `check_impedance` function to ensure the real part of the diagonal elements of the impedance matrix are greater than a threshold. I was a bit frustrated because I wound up duplicating `check_linear_damping` instead of finding a way to integrate them more cleanly into one function. The issues making integration challenging are:

 - For `check_linear_damping`, we want to modify the linear friction variable in the `hydro_data` `DataSet`
 - For `check_impedance`, we want to modify the real part of the the `np.ndarray`

Thus there's this discrepancy both in

1. The type of object you're working with (`DataSet` vs. `np.ndarray`)
2. The action you take (add to `orig.friction` vs. `np.real(orig)`)

2022-12-02 21:28 UTC, cmichelenstrofer commented on tests/test_integration.py
> +                                       optim_options={'maxiter': 3})
Awesome! And yeah it is better as two functions, the other option would be having a bunch of if-statements which would be much worst imo. The reality of supporting different workflows. But I do think these two workflows should be supported. IMO we could get rid of `from_floatingbody`, it is only one more line of code to be able to use `from_bem` and they are essentially the same workflow.

2022-12-02 22:30 UTC, ryancoe commented
Between 61fd5a1 and 0734bd3, I increased the scopes in `test_integration.py` (mostly `scope='module'`; see 83cc1566e365205f4374ba351aa2334ad9c8bd09) and now the CI runs in close to 1/2 the time! We should keep an eye on this and maybe even do the necessary steps to make sure we never rerun the same BEM across the whole test suite.

2022-12-02 22:35 UTC, ryancoe commented
@cmichelenstrofer - As discussed, this doesn't capture all of the tests identified in #158. However, I think it is at the right point to merge and be helpful for ongoing development. Before you merge, you may want to either (a) update #158 so that it only has the tests that this includes or (b) don't use this PR to close #158 (i.e., alter description). I'd recommend (a), because it feels good to close things out ;)

2022-12-14 23:24 UTC, cmichelenstrofer requested changes

2022-12-14 23:24 UTC, cmichelenstrofer commented on wecopttool/core.py
> +    def resid_fun(self, x_wec, x_opt, waves):
```suggestion
    def _resid_fun(self, x_wec, x_opt, waves):
```

2022-12-14 23:24 UTC, cmichelenstrofer commented on wecopttool/core.py
> +        """TODO"""
```suggestion
```

2022-12-14 23:24 UTC, cmichelenstrofer commented on wecopttool/core.py
> +            return self.resid_fun(x_wec, x_opt, waves)
```suggestion
            return self._resid_fun(x_wec, x_opt, waves)
```

2022-12-14 23:24 UTC, cmichelenstrofer commented on tests/test_core.py
> +        Zi = wot.hydrodynamic_impedance(data)
We still need a test for `wot.hydrodynamic_impedance`. Since that function is used here and is related, I would recommend making this class a test for both functions. And then adding a test specifically for `wot.hydrodynamic_impedance`. Ideally it would check values vs expected values, but at the very least check type/dimension.

2022-12-14 23:24 UTC, cmichelenstrofer commented on tests/test_integration.py
> +    bem_res = wec_from_bem.resid_fun(x_wec_0, x_opt_0, waves)
```suggestion
    bem_res = wec_from_bem._resid_fun(x_wec_0, x_opt_0, waves)
```

2022-12-14 23:24 UTC, cmichelenstrofer commented on tests/test_integration.py
> +    fb_res = wec_from_floatingbody.resid_fun(x_wec_0, x_opt_0, waves)
```suggestion
    fb_res = wec_from_floatingbody._resid_fun(x_wec_0, x_opt_0, waves)
```

2022-12-14 23:24 UTC, cmichelenstrofer commented on tests/test_integration.py
> +    imp_res = wec_from_impedance.resid_fun(x_wec_0, x_opt_0, waves)
```suggestion
    imp_res = wec_from_impedance._resid_fun(x_wec_0, x_opt_0, waves)
```

2022-12-14 23:24 UTC, cmichelenstrofer commented on tests/test_integration.py
>  def p_controller_pto():
Several fixtures don't have a docstring. They should have a short (one line) description of what the fixture is. This serves as a way of in-code documentation to make understanding the tests easier.

2022-12-14 23:24 UTC, cmichelenstrofer commented on tests/test_integration.py
> +kplim = -1e1
make this a fixture? Or move it to the top of the file?

2022-12-14 23:24 UTC, cmichelenstrofer commented on tests/test_integration.py
> +
Add a docstring explaining the purpose of this class (the common theme of the grouped tests).

2022-12-14 23:24 UTC, cmichelenstrofer commented on tests/test_integration.py
>  # TODO: convert some of the old tests to v2:
Should we keep these here? Since we're not planning on working on these in the near future maybe we can save these somewhere else? Maybe another file that doesn't start with "test_" ?

2022-12-15 14:40 UTC, ryancoe commented on tests/test_integration.py
> +kplim = -1e1
I tried to make this a fixture, but couldn't figure out how to make that work since it it also used here

```python
@pytest.mark.parametrize("bounds_opt",
                         [Bounds(lb=kplim, ub=0), ((kplim, 0),)])
```

2022-12-15 14:45 UTC, ryancoe commented on tests/test_integration.py
>  def p_controller_pto():
resolved with 18dc706fa11ef6027095dad9b6fc45acf2014a81

2022-12-15 14:45 UTC, ryancoe commented on tests/test_integration.py
> +kplim = -1e1
resolved with 49c9b47bf20dc35e1c3a1b119440e33d2da2c512

2022-12-15 14:53 UTC, ryancoe commented on tests/test_core.py
> +        Zi = wot.hydrodynamic_impedance(data)
Good point. In `test_core`, the `hydro_data` we work with is actually just made up ("synthetic"), so doing a meaningful test will be hard... should we switch to using real BEM data?

2022-12-15 15:48 UTC, ryancoe commented on tests/test_core.py
> +        Zi = wot.hydrodynamic_impedance(data)
Per discussion w. @cmichelenstrofer, we will have a somewhat trivial test for `wot.hydrodynamic_impedance` for the time being (e.g., check the shape). Will also add a `# TODO` to move to using a single `run_bem` throughout the test suite (fixture would have scope across `package` or `session` https://docs.pytest.org/en/6.2.x/fixture.html#fixture-scopes).

2022-12-15 15:58 UTC, ryancoe commented on tests/test_core.py
> +        Zi = wot.hydrodynamic_impedance(data)
resolved w. fea00b956c568ff2fdc8831b2ea999459ed7716e

2022-12-15 16:01 UTC, ryancoe commented on tests/test_integration.py
> +
resolved w. 18dc706fa11ef6027095dad9b6fc45acf2014a81

2022-12-15 16:03 UTC, ryancoe commented on tests/test_integration.py
>  # TODO: convert some of the old tests to v2:
let's delete for now, can always look back at history if we like. Resolved w. 4d8a7d1619b921245739f8ad27a940436f8ec690

2022-12-15 16:24 UTC, merged