WaveBot: update preprint DOI and paper accepted
SNL-WaterPower/WecOptTool pull request #194
Opened 2020-10-22 01:10 UTC by ryancoe

Update the DOI for the TechRxiv preprint and note acceptance of paper by _Journal of Ocean Engineering and Marine Energy._

2020-10-22 13:55 UTC, H0R5E requested changes
The content is fine, but I think we could present it more prominently. If you want to keep it this way, then please add a subsection header for the new content.

Happy to help implement my suggestions, if they sound good to you.

2020-10-22 13:55 UTC, H0R5E commented on docs/user/references.rst
> +
I'm not adverse to this content, but I think it should be on its own page, perhaps 2 pages. I would have a page for the main reference [numpy style](https://numpy.org/citing-numpy/) and a page for the other information called "Resources". We could even embed the webinar, if you wanted?

At very least, this needs to be given a sub-section header so that it does not get lost in the navigation.

2020-10-23 19:27 UTC, ryancoe commented on docs/user/references.rst
> +
@H0R5E - if you really don't mind, I would indeed appreciate it if you can show me what you mean by this.

2020-11-04 11:46 UTC, H0R5E approved these changes

2020-11-04 11:49 UTC, merged