Linear PTO
SNL-WaterPower/WecOptTool pull request #38
Opened 2022-01-27 17:01 UTC by cmichelenstrofer

## Description
Add a linear PTO. See #58

## Type of PR
- [ ] Bug fix
- [ ] Major change
- [x] New feature

## Checklist for PR
- [x] Authors read the [contribution guidelines](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [x] The pull request is from an issue branch (not main) on your fork to the [main branch in WecOptTool](https://github.com/SNL-WaterPower/WecOptTool). 
- [x] The authors have given the admins edit access
- [x] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [x] Added note in [Changelog](https://github.com/SNL-WaterPower/WecOptTool/blob/main/CHANGES.md)
- [x] Modified the documentation if applicable
- [x] Modified or added a new test
- [x] All tests pass
- [x] Documentation builds
- [x] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

## Additional details

2022-02-28 21:10 UTC, cmichelenstrofer commented
To Do:

- [ ] Convert example into a test (CC solution for electric quantities)
- [ ] Create an example frequency-dependent PTO impedance for the WaveBot
- [ ] Modify code to use frequency-dependent PTO impedance
- [ ] Create example/test case with the WaveBot

2022-03-14 21:28 UTC, cmichelenstrofer commented
Closes #58

2022-03-14 23:33 UTC, cmichelenstrofer commented
@ryancoe I only implemented the linear PTO for pseudospectral (unstructured) PTO. I started trying to implement the P and PI controller but... it will require a big change. We need to transform the impedance to go from `[velocity; force] -> [current, voltage]` rather than from `[velocity, current] -> [force, voltage]` (flow -> effort) like we have it right now. For the pseudospectral case the `x_opt` should be for force rather than current. I think we should open a new issue/PR for this.

2022-03-15 15:34 UTC, cmichelenstrofer commented
This is how to convert the impedance to the desired form: 
![Screen Shot 2022-03-15 at 09 33 36](https://user-images.githubusercontent.com/25060182/158414015-5bafe182-f476-4bbe-95bc-998272bb3750.png)

2022-03-15 15:36 UTC, cmichelenstrofer commented
Two options:

1. Ask users to provide the actual impedance and we convert it internally to the form above (Equation 3, I think GB calls this "ABC" form). 
2. Ask the user to provide the impedance in "ABC" form, and provide a helper function to convert from impedance to "ABC" form in case they need it.

2022-03-15 19:50 UTC, ryancoe commented
Per discussion w. @cmichelenstrofer, he will:

1. Implement two _base_ classes:
   - Mechanical PTO (currently exists in `main` branch)
   - Electrical PTO (as developed in this PR)
2. Implement sub-classes for each of these:
   - Pseudospectral ("unstructured")
   - P
   - PI

In the medium term, we will restructure `pto.py` to use a single base class and control whether mechanical or electrical power is considered based on whether or not the user passes an impedance matrix for the PTO (`if Z_pto is None: Z_pto = eye...`).

2022-03-15 19:50 UTC, ryancoe requested changes
Per discussion w. @cmichelenstrofer, he will:

1. Implement two _base_ classes:
   - Mechanical PTO (currently exists in `main` branch)
   - Electrical PTO (as developed in this PR)
2. Implement sub-classes for each of these:
   - Pseudospectral ("unstructured")
   - P
   - PI

In the medium term, we will restructure `pto.py` to use a single base class and control whether mechanical or electrical power is considered based on whether or not the user passes an impedance matrix for the PTO (`if Z_pto is None: Z_pto = eye...`).

2022-03-21 15:46 UTC, cmichelenstrofer commented
For PI controller Eq. 3 above could be written with only [v] on the RHS vector. This would results in smaller matrix and vector on the RHS. Will not do this now, for simplicity of implementation, but might want to reconsider when we do the restructuring of the`pto.py` module.

2022-04-05 15:26 UTC, cmichelenstrofer commented
@ryancoe this is (finally) ready for review

2022-04-05 17:24 UTC, ryancoe approved these changes
One set of very minor comments. As you've noted separately in #90, you've noticed something that we need to look at elsewhere, but I think this PR is big enough already and the rest can wait.

2022-04-05 17:24 UTC, ryancoe commented on wecopttool/pto.py
> +class PLinearPTO(_LinearPTO):
For consistency with `ProportionalPTO`, should this be names `ProportionalLinearPTO`? Really just asking here, not sure what is best. We also anticipate a major restructure/refactor of `pto.py` so it may not really matter in the long term.

2022-04-05 17:24 UTC, ryancoe commented on wecopttool/pto.py
> +class PILinearPTO(_LinearPTO):
Similarly, should this be named `ProportionalIntegralLinearPTO`?

2022-04-05 20:08 UTC, merged