post-processing xarray attributes updates
SNL-WaterPower/WecOptTool pull request #67
Opened 2022-03-02 17:18 UTC by ryancoe

## Description
I noticed while working on a case-study and making the plots that we should fix the following:

- [x] set the `attrs = {'long_name': ...}` whenever possible (e.g., for `time` and `omega`)
- [x] units for `ds.omega` should be `rad/s` not `(rad)`
- [x] Rerun the examples so they show these changes in their plots

## Type of PR
Minor update

## Checklist for PR
- [x] Authors read the [contribution guidelines](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [x] The pull request is from an issue branch (not main) on your fork to the [main branch in WecOptTool](https://github.com/SNL-WaterPower/WecOptTool). 
- [x] The authors have given the admins edit access
- [x] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- ~~Added note in [Changelog](https://github.com/SNL-WaterPower/WecOptTool/blob/main/CHANGES.md)~~
- ~~Modified the documentation if applicable~~
- ~~Modified or added a new test~~
- [x] All tests pass
- [x] Documentation builds
- ~~[Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)~~

2022-03-02 23:23 UTC, cmichelenstrofer requested changes
good changes but you missed a few "(rad)".

2022-03-02 23:23 UTC, cmichelenstrofer commented on wecopttool/core.py
>          attrs_vel = {'long_name': 'WEC velocity', 'units': 'm/s or (rad)/s'}
(rad) needs to be changed here too? maybe missed it in other places too (do "find/replace all"?)

2022-03-02 23:23 UTC, cmichelenstrofer commented on wecopttool/pto.py
>          attrs_vel = {'long_name': 'PTO velocity', 'units': 'm/s or (rad)/s'}
this (rad) should be replaced too. Just do "find all"

2022-03-07 21:29 UTC, ryancoe commented on wecopttool/core.py
>          attrs_vel = {'long_name': 'WEC velocity', 'units': 'm/s or (rad)/s'}
e3317ba0a22dad9b77b8568d4cb571bf4ce02555

2022-03-07 21:29 UTC, ryancoe commented on wecopttool/pto.py
>          attrs_vel = {'long_name': 'PTO velocity', 'units': 'm/s or (rad)/s'}
e3317ba0a22dad9b77b8568d4cb571bf4ce02555

2022-03-10 00:48 UTC, cmichelenstrofer approved these changes

2022-03-10 21:22 UTC, merged