Multidirectional waves
SNL-WaterPower/WecOptTool pull request #83
Opened 2022-03-16 23:22 UTC by dtgaebe

## Description
Implemented a new function `subsetclose()` which checks if an entire array `isclose()` to a subset in a second array and returns the indices of the respective entries from the second array. This function is used to check if the directions in `waves` are available in the BEM solution. Next only the right wave direction dimensions of the BEM solution are picked to create the `wave_excitation()`. This enables the appropriate excitation force coefficients for the multidirectional waves. This resolves issues #80, #81 and #82 

## Type of PR
- [x] Bug fix
- [ ] Major change
- [x] New feature

## Checklist for PR
- [x] Authors read the [contribution guidelines](https://github.com/SNL-WaterPower/WecOptTool/blob/main/.github/CONTRIBUTING.md)
- [x] The pull request is from an issue branch (not main) on your fork to the [main branch in WecOptTool](https://github.com/SNL-WaterPower/WecOptTool). 
- [x] The authors have given the admins edit access
- [ ] All changes adhere to the style guide including PEP8, Docstrings, and Type Hints.
- [x] Added note in [Changelog](https://github.com/SNL-WaterPower/WecOptTool/blob/main/CHANGES.md)
- [ ] Modified the documentation if applicable
- [ ] Modified or added a new test
- [ ] All tests pass
- [ ] Documentation builds
- [ ] [Reference or close any relevant issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

## Additional details
Include any relevant context and describe any validation and verification efforts.

2022-03-16 23:43 UTC, dtgaebe commented
I tested the code on my local copy with different multidirection and regular waves. I'm not sure how the Checks work and if I would need to edit an existing check?

2022-03-22 03:04 UTC, ryancoe requested changes
I would say probably remove [`wavebot_reg_irreg_waves.ipynb`](https://github.com/SNL-WaterPower/WecOptTool/pull/83/files#diff-5451cb985f62ce45c9964a056d02cd1cc0f8a97f9e39463784aa236b1f851d57) before merging and move any checks you're doing manually there to [`test_wecopttool.py`](https://github.com/SNL-WaterPower/WecOptTool/pull/83/files#diff-4279134dae5e69985e54c5bbdfef7f6feb917b921511d979bdccf01674ac5c6c).

2022-03-22 03:04 UTC, ryancoe commented on wecopttool/waves.py
> +    assert len(np.atleast_1d(np.array(direction).squeeze()))==1,\
I had to look it up (looks like @cmichelenstrofer already knew this), but apparently `assert` should test something that will only break if the program itself is messed up, not it the user gives a bad input. Thus, please change this check to use a `raise` statement.

https://stefan.sofa-rockers.org/2018/04/16/assertions-and-exceptions/

2022-03-24 17:47 UTC, cmichelenstrofer commented
@dtgaebe Some resources on 

- Brief summary of main equation(we might want to have something at this level in our own documentation): https://wec-sim.github.io/WEC-Sim/master/theory/theory.html#wave-spectra
- Detailed explanation (see equation 12, 13): https://www.oceanopticsbook.info/view/surfaces/level-2/wave-variance-spectra-theory

2022-03-24 22:42 UTC, cmichelenstrofer requested changes
Looks good! Almost all my comments are on style, which I know I said not to focus on at first. But now is the time to fix it. Additionally:

- I would add a test for the irregular waves using subset of BEM directions.

2022-03-24 22:42 UTC, cmichelenstrofer commented on wecopttool/core.py
> +        for b in B) for a in A)
Nice succinct way of doing it. I'm a big fan of list comprehensions, but in this case since both values each creates the same two nested loops and because the comprehensions are a bit complex, it might be better to actually write out the for-loops. Up to you. Also, what would happen if the two arrays where not "nice"? This shouldn't happen in our code, but what if B has repeated elements so that an element is a is close to more than one value in B? Might want to do some initial checks on A and B (increasing order? between -pi and pi? etc). Also can we use `np.where` so that we don't need to convert B to a list?

2022-03-24 22:42 UTC, cmichelenstrofer commented on wecopttool/core.py
> +def subsetclose(A, B, rtol=1.e-5, atol=1.e-8, equal_nan=False):
also variables should not have capital letters, and ideally not be single letters. See [pep8](https://www.python.org/dev/peps/pep-0008/)

2022-03-24 22:42 UTC, cmichelenstrofer commented on wecopttool/waves.py
> +    assert len(np.atleast_1d(np.array(direction).squeeze()))==1,\
good point. Probably a `valueError` is the most appropriate here.

2022-03-24 22:42 UTC, cmichelenstrofer commented on tests/test_wecopttool.py
> +        _, _ = wot.wave_excitation(wec.hydro, wrong_wave)
Nice! We haven't done this before. It is good to add tests that should fail!

2022-03-24 22:43 UTC, cmichelenstrofer commented
Are you planing on doing the validation (#57) in this PR? If so you need to add tests that checks that multidirectional waves gives us the answers we expect.

2022-03-24 23:26 UTC, dtgaebe commented on tests/test_wecopttool.py
> +        _, _ = wot.wave_excitation(wec.hydro, wrong_wave)
@ryancoe must receive credit here I think. But I will have that in mind!

2022-03-25 18:46 UTC, dtgaebe commented on wecopttool/core.py
> +        for b in B) for a in A)
Thank you for the feedback @cmichelenstrofer ! I'm writing the loops out.
I agree that we need to check the arrays for uniqueness.
I think ascending or not doesn't matter as long as we pass the index that comes out of this function it should match.
I was thinking that `subsetclose` might also be used for the wave / BEM frequencies `omega`, thus I would check for between -pi and pi at a different spot? Rather in the waves?

2022-03-25 19:13 UTC, dtgaebe commented on wecopttool/core.py
> +        for b in B) for a in A)
That makes sense with the frequencies.

Right, but I was thinking that if we would check for pi/-pi we cannot use `subsetclose' for frequencies. So I would rather check for pi/-pi at a different spot in the code, like in `waves.py`. But I think due to the conversion from `_degrees_to_radians` this is taken care of anyway.

2022-04-07 16:02 UTC, cmichelenstrofer commented on wecopttool/waves.py
> +
let's change this to raising a value or type error instead of assert

2022-04-07 18:21 UTC, closed without merging